import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import Header from "@/components/sidebar/Header";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { TopNav } from "@/components/header/top-nav";
import Sidebar from "@/components/sidebar/Sidebar";
import { Providers } from "@/redux/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <SidebarProvider>
              <Sidebar />
              <main className="w-full">
                {/* <TopNav /> */}

                {children}
              </main>
            </SidebarProvider>
          </ThemeProvider>
        </body>
      </html>
    </Providers>
  );
}
